sudo: false
language: node_js

script:
  - make clean build test

matrix:
  include:
    - node_js: "stable"
    - node_js: "4"
    - node_js: "6"
    - node_js: "8"
    - node_js: "9"
    - node_js: "10"
    - node_js: "12"
